# Generated by Django 3.1.1 on 2020-09-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20200929_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
